---
apiVersion: v1
kind: Namespace
metadata:
  name: vk-workloads
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vk-remote-sa
  namespace: vk-workloads
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vk-remote-role
rules:
- apiGroups: [""]
  resources: [pods, pods/status, pods/log]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [""]
  resources: [secrets, configmaps, serviceaccounts, persistentvolumeclaims, services]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
- apiGroups: [""]
  resources: [namespaces]
  verbs: [get, list, create]
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vk-remote-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vk-remote-role
subjects:
- kind: ServiceAccount
  name: vk-remote-sa
  namespace: vk-workloads
